#!/bin/bash

# ─────────────────────────────────────────────
#  copyparty-mount-setup.sh
#  Install or uninstall a .desktop toggle for
#  an rclone-mounted copyparty remote.
# ─────────────────────────────────────────────

set -euo pipefail

APPS_DIR="$HOME/.local/share/applications"
BIN_DIR="$HOME/.local/bin"

# ── helpers ───────────────────────────────────

die()  { echo "ERROR: $*" >&2; exit 1; }
info() { echo "  $*"; }

check_deps() {
    command -v rclone &>/dev/null || die "rclone is not installed or not in PATH."
}

slugify() {
    # Turn a remote name into a safe filename fragment
    echo "$1" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-' | sed 's/-$//'
}

desktop_path() { echo "$APPS_DIR/copyparty-${1}.desktop"; }
helper_path()  { echo "$BIN_DIR/copyparty-toggle-${1}.sh"; }

# ── install ───────────────────────────────────

do_install() {
    check_deps

    echo ""
    echo "╔══════════════════════════════════════╗"
    echo "║   Copyparty Rclone Mount — Install   ║"
    echo "╚══════════════════════════════════════╝"
    echo ""

    read -rp "  Rclone remote name : " REMOTE_NAME
    [[ -n "$REMOTE_NAME" ]] || die "Remote name cannot be empty."

    read -rp "  Mount point (path)  : " MOUNT_POINT
    [[ -n "$MOUNT_POINT" ]] || die "Mount point cannot be empty."

    # Expand ~ manually (read -r doesn't expand it)
    MOUNT_POINT="${MOUNT_POINT/#\~/$HOME}"

    SLUG="$(slugify "$REMOTE_NAME")"
    DESKTOP_FILE="$(desktop_path "$SLUG")"
    HELPER_SCRIPT="$(helper_path "$SLUG")"

    if [[ -f "$DESKTOP_FILE" ]]; then
        read -rp "  A desktop entry for '$REMOTE_NAME' already exists. Overwrite? [y/N] " yn
        [[ "${yn,,}" == "y" ]] || { echo "Aborted."; exit 0; }
    fi

    # Create directories
    mkdir -p "$APPS_DIR" "$BIN_DIR" "$MOUNT_POINT"

    # ── write the toggle helper script ──────────

    cat > "$HELPER_SCRIPT" <<HELPER
#!/bin/bash
# Auto-generated by copyparty-mount-setup.sh
# Toggle rclone mount for remote: ${REMOTE_NAME}

REMOTE="${REMOTE_NAME}"
MOUNT_POINT="${MOUNT_POINT}"

notify() {
    notify-send --app-name="Copyparty" --icon="\$1" "Copyparty" "\$2" 2>/dev/null || true
}

if mountpoint -q "\$MOUNT_POINT"; then
    # Currently mounted → unmount
    if fusermount -u "\$MOUNT_POINT" 2>/dev/null || umount "\$MOUNT_POINT" 2>/dev/null; then
        notify "network-offline" "Unmounted \$REMOTE"
    else
        notify "dialog-error" "Failed to unmount \$REMOTE"
        exit 1
    fi
else
    # Not mounted → mount
    mkdir -p "\$MOUNT_POINT"
    if rclone mount --vfs-cache-mode writes --dir-cache-time 5s "\${REMOTE}:" "\$MOUNT_POINT" --daemon; then
        notify "network-transmit" "Mounted \$REMOTE at \$MOUNT_POINT"
    else
        notify "dialog-error" "Failed to mount \$REMOTE"
        exit 1
    fi
fi
HELPER

    chmod +x "$HELPER_SCRIPT"

    # ── write the .desktop file ─────────────────

    cat > "$DESKTOP_FILE" <<DESKTOP
[Desktop Entry]
Version=1.0
Type=Application
Name=Copyparty — ${REMOTE_NAME}
Comment=Toggle rclone mount for ${REMOTE_NAME} at ${MOUNT_POINT}
Exec=${HELPER_SCRIPT}
Icon=folder-remote
Terminal=false
Categories=Network;FileTransfer;
Keywords=copyparty;rclone;mount;${REMOTE_NAME};
DESKTOP

    # Refresh desktop database if available
    update-desktop-database "$APPS_DIR" 2>/dev/null || true

    echo ""
    echo "  ✓ Helper script : $HELPER_SCRIPT"
    echo "  ✓ Desktop entry : $DESKTOP_FILE"
    echo "  ✓ Mount point   : $MOUNT_POINT"
    echo ""
    echo "  Click the app in your launcher to toggle the mount."
    echo ""
}

# ── uninstall ─────────────────────────────────

do_uninstall() {
    echo ""
    echo "╔════════════════════════════════════════╗"
    echo "║   Copyparty Rclone Mount — Uninstall   ║"
    echo "╚════════════════════════════════════════╝"
    echo ""

    # Discover installed entries
    mapfile -t DESKTOPS < <(find "$APPS_DIR" -maxdepth 1 -name "copyparty-*.desktop" 2>/dev/null | sort)

    if [[ ${#DESKTOPS[@]} -eq 0 ]]; then
        echo "  No copyparty desktop entries found. Nothing to remove."
        exit 0
    fi

    echo "  Installed copyparty entries:"
    echo ""
    for i in "${!DESKTOPS[@]}"; do
        LABEL="$(grep -m1 '^Name=' "${DESKTOPS[$i]}" | cut -d= -f2-)"
        printf "    [%d] %s\n" "$((i+1))" "$LABEL"
    done
    echo "    [a] All of the above"
    echo ""

    read -rp "  Which entry to remove? " CHOICE

    remove_entry() {
        local DF="$1"
        local SLUG
        SLUG="$(basename "$DF" .desktop | sed 's/^copyparty-//')"
        local HELPER
        HELPER="$(helper_path "$SLUG")"

        # Unmount if currently mounted
        if [[ -f "$HELPER" ]]; then
            local MP
            MP="$(grep -m1 '^MOUNT_POINT=' "$HELPER" | cut -d'"' -f2)"
            if [[ -n "$MP" ]] && mountpoint -q "$MP" 2>/dev/null; then
                info "Unmounting $MP …"
                fusermount -u "$MP" 2>/dev/null || umount "$MP" 2>/dev/null || true
            fi
            rm -f "$HELPER"
            info "Removed helper : $HELPER"
        fi

        rm -f "$DF"
        info "Removed desktop : $DF"
    }

    if [[ "${CHOICE,,}" == "a" ]]; then
        for DF in "${DESKTOPS[@]}"; do remove_entry "$DF"; done
    elif [[ "$CHOICE" =~ ^[0-9]+$ ]] && (( CHOICE >= 1 && CHOICE <= ${#DESKTOPS[@]} )); then
        remove_entry "${DESKTOPS[$((CHOICE-1))]}"
    else
        die "Invalid choice."
    fi

    update-desktop-database "$APPS_DIR" 2>/dev/null || true

    echo ""
    echo "  ✓ Uninstall complete."
    echo ""
}

# ── entrypoint ────────────────────────────────

case "${1:-}" in
    install)   do_install   ;;
    uninstall) do_uninstall ;;
    *)
        echo ""
        echo "  Usage: $(basename "$0") {install|uninstall}"
        echo ""
        echo "  install    Create a .desktop toggle for a copyparty rclone mount"
        echo "  uninstall  Remove one or all copyparty .desktop entries"
        echo ""
        exit 1
        ;;
esac
